### ISSUE TITLE
Option to count tracker entries as chapters or volumes

### ISSUE THREAD

**Issue by dan-malprod** [tachiyomiorg/tachiyomi#10395]
### Issue
There are several manga that I have read that have entries (chapters) as entire volumes instead as individual chapters. This poses an issue when using trackers as the tracker does not know this.

### Solution
An option should be presented when enabling a tracker, where you choose wether to frack entries as chapters (default) or volumes.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an official extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/extensions/issues/new/choose).
- [X] I have updated the app to version **[0.15.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by THElegend5** [comment]
Duplicate of #8143
