### ISSUE TITLE
Manga chapters history tracking. 

### ISSUE THREAD

**Issue by Taijefx34** [tachiyomiorg/tachiyomi#5576]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/tag/v0.11.1)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

For example I have a manga with 25 chapters.
When I finished reading the 1st chapter Tachiyomi adds it to History.
Then I'm finished reading the 2nd one and Tachiyomi just removes 1st one from history and adds to History only 2nd instead.
It happens with all other chapters.

The enhancement is about to track every chapter of manga.

### Other details

![Screenshot_20210719-030540_Tachiyomi](https://user-images.githubusercontent.com/48826466/126083709-4ea0a4d1-b5cd-45dc-999e-454577d21228.jpg)
![Screenshot_20210719-030754_Tachiyomi](https://user-images.githubusercontent.com/48826466/126083712-9444d2bc-e70f-4bcc-802a-b8a96e3bea5e.jpg)
![Screenshot_20210719-030545_Tachiyomi](https://user-images.githubusercontent.com/48826466/126083714-665a32e1-c5da-4320-aab6-b17c010223f9.jpg)
![Screenshot_20210719-030548_Tachiyomi](https://user-images.githubusercontent.com/48826466/126083719-54e2adcb-8847-4404-99eb-953e21878cf7.jpg)

**Comment by zayin02** [comment]
What are you even talking about?

**Comment by Taijefx34** [comment]
> What are you even talking about, you just said what Tachiyomi already does?

Just look at the screenshots.
*Ch. 1 was added to history*
Then I "read" the 2nd one.
*Ch. 2 was added to history*

**Comment by zayin02** [comment]
It was marked as read, the history just takes you to the "latest" chapter you read. It didn't delete anything

**Comment by Taijefx34** [comment]
So what's my request about is tracking every chapters of 1manya independently. I know Tachiyomi's history is not for that, but it will be fine.
Anyway thanks for reply

**Comment by arkon** [comment]
As I already answered on Discord, the in-app history is not meant for this sort of tracking. Use an actual tracking service for retaining that sort of data.
