### ISSUE TITLE
An Epic Manga Timer

### ISSUE THREAD

**Issue by Itz1ASh** [tachiyomiorg/tachiyomi#7015]
### Describe your suggested feature

Add a feature for manga where it tells you how long you've spent reading,  it'll help to now how much time we've lost while looking at glorified doddles

### Other details

Practically speaking...
you would need to account for sudden afks leaving the screen on (on settings where you can change how long until the system stops counting 20- 60 seconds could be the theshold). Also for the manga you already have a lot of progress for you could figure out the average across the newly read ones ( or get very slight results from other manga you've read) and put it across for all the previous chapters. I don't think there is any way around for completely finished manga (how long they thought it personally took them) I know it's a lot of work for a small gimmick but it'd be pretty cool

### Acknowledgements

- [ ] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with an extension, I should be opening an issue in the [extensions repository](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
- [X] I have updated the app to version **[0.13.4](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
Duplicate of #115
